[package]
name = 'PseudoLp'
version = '1.0.0'

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main', subdir = 'aptos-move/framework/aptos-framework' }

[addresses]
admin = "fc9e2d5d9d640c0dda9bdeac5db8a15076f329ae6274a8b8d9506ddcabea18a7"
resource = "915d6c8dcda99c249d8a2231d6a4a193747375fdb6f599a9cb96a8597d2aae88"
